version: '3.8'

services:
  python-executor:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s